Feature/zaken overview
Gemeente-DenHaag/mijndenhaag-pwa pull request #48
Opened 2021-03-13 14:03 UTC by GewoonMaarten

2021-03-25 19:41 UTC, ogjtech requested changes

2021-03-25 19:41 UTC, ogjtech commented on src/components/ZaakList/index.tsx
> +          key={zaak.uuid}
Where does this property go? I do not see it in the `ZaakCardProps` class, nor in the `ZaakCard` class.

2021-03-25 19:41 UTC, ogjtech commented on src/model/openzaak/index.ts
> +  next?: string | null
Specifying `| null` here is redundant if the property is already nullable by adding the `?`  suffix to the property definition.

2021-03-25 19:41 UTC, ogjtech commented on src/utils/api.ts
> +export abstract class OpenZaakApi {
I get doing it this way currently, but _please_ try convincing the team behind the production API to add functionalities with which we can generate these requests. The API will get updated and having to update the requests everywhere is tedious and more time consuming than it needs to be.

2021-03-26 22:36 UTC, mjcarsjens commented on src/components/ZaakList/index.tsx
> +          key={zaak.uuid}
https://reactjs.org/docs/lists-and-keys.html#keys

`key` is a built-in React prop used to identify the item. Basically, when something changes in a component React uses the `key` prop to identify which component should be re-rendered. Some more background information:

- https://kentcdodds.com/blog/understanding-reacts-key-prop
- https://dev.to/francodalessio/understanding-the-importance-of-the-key-prop-in-react-3ag7

When you loop over elements being rendered, as is the case here, you always should add a unique `key` prop to each item being rendered.

The `key` prop is not actually passed along to the component for a developer to use, so my feeling is it should not be in the `ZaakCardProps`. 

A way to better indicate that we are dealing with React components here could be to type the component as follows:
`const ZaakCard: React.FC<ZaakCardProps> = ({ ...`

However, a quick google search on React.FC typing seems to indicate there are some problems with this, so while this would make the typing better I feel like this is something we might need to read a bit more about.

2021-03-26 22:36 UTC, mjcarsjens commented on src/model/openzaak/index.ts
> +  next?: string | null
Not sure whether a `null` value is necessary in this use-case, but the optional suffix (`?`) does not mean a property is nullable.

the optional (`?`) suffix makes it possible to have no value assigned to a variable, which in JS translates to being `undefined`.
However, there is a distinction between `null` and `undefined`, where `undefined` means that a variable literally has not been defined, whereas `null` is an actual assigned value. 

For example:

```
function foo(bar?: string) {
    console.info(bar);
}

foo("Hello World!"); // OK
foo(null); // Error
foo(undefined); // OK
foo() // OK

```
So `bar?: string` is the same as writing out `bar: string | undefined`, but not the same as `bar: string | null`. 

https://stackoverflow.com/questions/57243477/can-an-optional-parameter-be-null-in-typescript

2021-03-26 22:37 UTC, mjcarsjens commented on src/components/ZaakList/index.tsx
> +          key={zaak.uuid}
I just looked at our component library and there we are typing our function components, so we should be doing the same here.

2021-03-27 10:28 UTC, GewoonMaarten commented on src/components/ZaakList/index.tsx
> +          key={zaak.uuid}
Key is required by React for arrays otherwise it will throw an error in the console. I've updated the type to use React.FC<ZaakCardProps>.

2021-03-27 10:40 UTC, GewoonMaarten commented on src/model/openzaak/index.ts
> +  next?: string | null
This type was generated by the script in package.json.

2021-03-27 10:46 UTC, bddjong commented
> To test this PR you manually need to a bearer token to the session storage of the page. The key must be called _token_. The token must not include the _Bearer_ string.

I'll add an issue to complete the implementation of the mock login. Which should be possible now that we have the mock login UI as well as the login endpoint.

2021-03-27 11:09 UTC, bddjong approved these changes

2021-03-27 12:20 UTC, GewoonMaarten commented on src/utils/api.ts
> +export abstract class OpenZaakApi {
That would be nice. I've moved the API call out of the ZaakList for better Separation Of Concerns.

2021-03-27 12:31 UTC, bddjong requested changes

2021-03-27 12:31 UTC, bddjong commented on src/pages/index.tsx
> +        headerText='bla'
Can we use text more faithful to the design :D

2021-03-27 12:33 UTC, GewoonMaarten commented on src/pages/index.tsx
> +        headerText='bla'
Fine.... but whats wrong with bla? 😔

2021-03-27 12:47 UTC, DanielvanVliet reviewed
Looks good!

2021-03-27 12:57 UTC, GewoonMaarten commented on package.json
> +    "start": "gatsby develop --verbose",
It helped me with debugging.

2021-03-27 13:02 UTC, bddjong approved these changes

2021-03-27 13:04 UTC, DanielvanVliet commented on package.json
> +    "start": "gatsby develop --verbose",
Ok sure won't hurt

2021-03-27 13:04 UTC, DanielvanVliet approved these changes

2021-03-27 13:24 UTC, joostvanviegen commented
I got two errors when trying to run:
`TypeError [ERR_INVALID_URL]: Invalid URL: undefined/home
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at Object.exports.default (/home/joost/werk/mijndenhaag-pwa/node_modules/got/dist/source/core/utils/options-to-url.js:35:17)
    at normalizeArguments (/home/joost/werk/mijndenhaag-pwa/node_modules/got/dist/source/core/index.js:480:51)
    at got (/home/joost/werk/mijndenhaag-pwa/node_modules/got/dist/source/create.js:112:39)
    at Object.exports.createPages (/home/joost/werk/mijndenhaag-pwa/gatsby-node.ts:35:43)
    at runAPI (/home/joost/werk/mijndenhaag-pwa/node_modules/gatsby/src/utils/api-runner-node.js:483:22)
    at Promise.catch.decorateEvent.pluginName (/home/joost/werk/mijndenhaag-pwa/node_modules/gatsby/src/utils/api-runner-node.js:634:13)
    at Promise._execute (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/promise.js:103:10)
    at /home/joost/werk/mijndenhaag-pwa/node_modules/gatsby/src/utils/api-runner-node.js:632:16
    at tryCatcher (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/util.js:16:23) {
  input: 'undefined/home',
  code: 'ERR_INVALID_URL'
}` Yes, I have renamed the .env.example to .env.development.

The other one is that the steplabel component cannot be located for some reason.
` ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

ERROR in /home/joost/werk/mijndenhaag-pwa/node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx(3,31):
3:31 Cannot find module '../StepIcon/StepIcon' or its corresponding type declarations.
    1 | import React from "react";
    2 | import MaterialStepLabel from "@material-ui/core/StepLabel";
  > 3 | import { StepIconProps } from "../StepIcon/StepIcon";
      |                               ^
    4 | import BaseProps from "@gemeente-denhaag/baseprops";
    5 | 
    6 | export interface StepLabelProps extends BaseProps {

File: node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx

failed Building development bundle - 11.999s
ERROR in /home/joost/werk/mijndenhaag-pwa/node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx
ERROR in /home/joost/werk/mijndenhaag-pwa/node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx(3,31):
3:31 Cannot find module '../StepIcon/StepIcon' or its corresponding type declarations.
    1 | import React from "react";
    2 | import MaterialStepLabel from "@material-ui/core/StepLabel";
  > 3 | import { StepIconProps } from "../StepIcon/StepIcon";
      |                               ^
    4 | import BaseProps from "@gemeente-denhaag/baseprops";
    5 | 
    6 | export interface StepLabelProps extends BaseProps {

webpack compiled with 1 error
verbose Transition to "waiting"`

2021-03-27 13:39 UTC, GewoonMaarten commented
> I got two errors when trying to run:
> 
> ```
> TypeError [ERR_INVALID_URL]: Invalid URL: undefined/home
>     at onParseError (internal/url.js:257:9)
>     at new URL (internal/url.js:333:5)
>     at Object.exports.default (/home/joost/werk/mijndenhaag-pwa/node_modules/got/dist/source/core/utils/options-to-url.js:35:17)
>     at normalizeArguments (/home/joost/werk/mijndenhaag-pwa/node_modules/got/dist/source/core/index.js:480:51)
>     at got (/home/joost/werk/mijndenhaag-pwa/node_modules/got/dist/source/create.js:112:39)
>     at Object.exports.createPages (/home/joost/werk/mijndenhaag-pwa/gatsby-node.ts:35:43)
>     at runAPI (/home/joost/werk/mijndenhaag-pwa/node_modules/gatsby/src/utils/api-runner-node.js:483:22)
>     at Promise.catch.decorateEvent.pluginName (/home/joost/werk/mijndenhaag-pwa/node_modules/gatsby/src/utils/api-runner-node.js:634:13)
>     at Promise._execute (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/debuggability.js:384:9)
>     at Promise._resolveFromExecutor (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/promise.js:518:18)
>     at new Promise (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/promise.js:103:10)
>     at /home/joost/werk/mijndenhaag-pwa/node_modules/gatsby/src/utils/api-runner-node.js:632:16
>     at tryCatcher (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/util.js:16:23)
>     at Object.gotValue (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/reduce.js:166:18)
>     at Object.gotAccum (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/reduce.js:155:25)
>     at Object.tryCatcher (/home/joost/werk/mijndenhaag-pwa/node_modules/bluebird/js/release/util.js:16:23) {
>   input: 'undefined/home',
>   code: 'ERR_INVALID_URL'
> }`
> ```
> 
> Yes, I have renamed the .env.example to .env.development.
> 
> The other one is that the steplabel component cannot be located for some reason.
> 
> ```
> ` ERROR #98123  WEBPACK
> Generating development JavaScript bundle failed
> ERROR in /home/joost/werk/mijndenhaag-pwa/node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx(3,31):
> 3:31 Cannot find module '../StepIcon/StepIcon' or its corresponding type declarations.
>     1 | import React from "react";
>     2 | import MaterialStepLabel from "@material-ui/core/StepLabel";
>   > 3 | import { StepIconProps } from "../StepIcon/StepIcon";
>       |                               ^
>     4 | import BaseProps from "@gemeente-denhaag/baseprops";
>     5 | 
>     6 | export interface StepLabelProps extends BaseProps {
> File: node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx
> failed Building development bundle - 11.999s
> ERROR in /home/joost/werk/mijndenhaag-pwa/node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx
> ERROR in /home/joost/werk/mijndenhaag-pwa/node_modules/@gemeente-denhaag/steplabel/StepLabel.tsx(3,31):
> 3:31 Cannot find module '../StepIcon/StepIcon' or its corresponding type declarations.
>     1 | import React from "react";
>     2 | import MaterialStepLabel from "@material-ui/core/StepLabel";
>   > 3 | import { StepIconProps } from "../StepIcon/StepIcon";
>       |                               ^
>     4 | import BaseProps from "@gemeente-denhaag/baseprops";
>     5 | 
>     6 | export interface StepLabelProps extends BaseProps {
> webpack compiled with 1 error
> verbose Transition to "waiting"
> ```

The first error is probably a problem with your .env file. Have you removed the top line? The second is a problem is related to this https://github.com/Gemeente-DenHaag/denhaag-component-library/pull/116

2021-03-27 14:00 UTC, merged