Sprint 7 merge 1
Gemeente-DenHaag/mijndenhaag-pwa pull request #49
Opened 2021-03-20 09:50 UTC by DanielvanVliet

This PR contains the following issues:

- [Mock Login #6 ](https://github.com/Gemeente-DenHaag/mijndenhaag-pwa/issues/6)
- [Side navigation #20](https://github.com/Gemeente-DenHaag/mijndenhaag-pwa/issues/20)
- [Page Header #17](https://github.com/Gemeente-DenHaag/mijndenhaag-pwa/issues/17)

2021-03-20 14:17 UTC, bddjong requested changes

2021-03-20 14:17 UTC, bddjong commented on CONTRIBUTING.md
> +When you make a PR you will need to sign our [Contributor License Agreement](CLA.md). Make sure to check with your employer if you have permission to sign before contributing.
CLA will not be added to our repositories. This PR fixes the docs https://github.com/Gemeente-DenHaag/mijndenhaag-pwa/pull/50

2021-03-20 14:20 UTC, bddjong requested changes

2021-03-20 14:20 UTC, bddjong commented on src/components/SideNav/index.tsx
> +// https://github.com/Gemeente-DenHaag/denhaag-component-library/issues/101  and
These issues have been closed after we concluded they shouldn't be implemented. Should this be fixed another way? @GewoonMaarten

2021-03-26 22:46 UTC, mjcarsjens commented on src/components/SideNav/index.tsx
> +// https://github.com/Gemeente-DenHaag/denhaag-component-library/issues/101  and
Kinda, we concluded that these should only be implemented when deemed necessary, and not in a global manner for all components. If there is a use-case for `aria-label` and `component` here we should add them to the allowed `props` of the component, but only the values we deem `necessary` should be allowed. So if we conclude we need these here for them to work then we should at least add the `aria-label: string` and `component: Link` to the ListItem component for now.

2021-03-26 22:46 UTC, mjcarsjens commented on src/components/SideNav/index.tsx
> +// TODO Temporary styling, remove when design tokens is done.
Nitpicking here but the convention for these type of comments is `TODO:` with the `:`. 
This way they might not be picked up by (certain) syntax highlighters etc.

2021-03-26 22:55 UTC, mjcarsjens commented
Quick question: is the linter configuration here working or are we running a different linter config for the PWA? 

I noticed the lack of `;` line-endings here, while these are used in our component library.

2021-03-27 10:35 UTC, bddjong commented
> Quick question: is the linter configuration here working or are we running a different linter config for the PWA?
> 
> I noticed the lack of `;` line-endings here, while these are used in our component library.

The configuration is working, but we're using a slightly different config from the component library. We have an issue to enforce a consistent style configuration for all three repositories.
https://github.com/Gemeente-DenHaag/mijndenhaag-pwa/issues/52
Which combines well with a consistent Husky config issue
https://github.com/Gemeente-DenHaag/mijndenhaag-pwa/issues/46

2021-03-27 12:43 UTC, bddjong approved these changes

2021-03-27 13:16 UTC, GewoonMaarten commented on src/components/SideNav/index.tsx
> +// TODO Temporary styling, remove when design tokens is done.
Updated

2021-03-27 13:16 UTC, GewoonMaarten commented on src/components/SideNav/index.tsx
> +// https://github.com/Gemeente-DenHaag/denhaag-component-library/issues/101  and
Updated

2021-03-27 14:09 UTC, joostvanviegen commented on src/components/TopNavigation/index.tsx
> +    <Link to='/404/'>
Wouldn't it be redundant to explicitly point to a not found page instead of an url which does not exist yet and also yields a not found page?

2021-03-27 14:20 UTC, joostvanviegen approved these changes

2021-03-27 15:04 UTC, GewoonMaarten approved these changes

2021-04-02 11:40 UTC, mjcarsjens approved these changes

2021-04-02 11:40 UTC, mjcarsjens commented on src/components/Header/index.tsx
> +// @ts-ignore   This is not a regular component, which ts doesn't like
Tip: [StackOverflow post about this issue](https://stackoverflow.com/a/45887328)

2021-04-02 11:40 UTC, mjcarsjens commented on src/components/Icons/common.ts
> +interface IIconProps {
Quick question: why are we calling it `IIcon`?

2021-04-02 11:40 UTC, mjcarsjens commented on src/components/TopNavigation/index.tsx
> +    <Link to='/404/'>
Fair point, personally I like simply linking to `#` for mock links but that's a bit of personal preference

2021-04-02 11:40 UTC, mjcarsjens commented on src/components/TopNavigation/index.tsx
> +    <Link to='/404/'>
(As is done on the `ZaakCard` component)

2021-04-03 08:23 UTC, GewoonMaarten commented on src/components/Icons/common.ts
> +interface IIconProps {
The first I stands for Interface. This is an convention in C#, I don't know if its used in Typescript.

2021-04-03 09:02 UTC, merged